---
title: "Rworksheet_Talon#3a"
author: "Cedric Mikhail Talon"
date: "2023-10-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r name, echo=FALSE}

#1. There is a built-in vector LETTERS contains the uppercase letters of the alphabet
#and letters which contains the lowercase letters of the alphabet.


uppercase_letters <- LETTERS [seq(1:26)]
uppercase_letters

lowercase_letters <- letters [seq(1:26)]
lowercase_letters


#a. You need to produce a vector that contains the first 11 letters.

firstLetters <- head(letters,11)
firstLetters


#b. Produce a vector that contains the odd numbered letters.

odd_Letters <- letters[seq(1,26,2)]
odd_Letters

#c. Produce a vector that contains the vowels


vowel_Letters <- letters[c(1,5,9,15,21)]
vowel_Letters


#d. Produce a vector that contains the last 5 lowercase letters.

lastsmall_letters <- tail(letters,5)
lastsmall_letters


#e. Produce a vector that contains letters between 15 to 24 letters in lowercase.

mid_Letters <-letters[c(15:24)]
mid_Letters



#2. Create a vector(not a dataframe) with the average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average
#temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees

#a. What is the R code and its result for creating a character vector for the city/town
#of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City? Name the
#object as city. The names should follow the same order as in the instruction.

city <- c("Tuguegarao City", "Manila", "Iloilo City"," Tacloban", "Samal Island", "Davao City")
city

#b. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.
#Name the object as temp. Write the R code and its output. Numbers should also follow
#what is in the instruction.

temp <- c(42, 39, 34, 34, 30, 27)
temp

#c. Create a dataframe to combine the city and the temp by using ‘data.frame(). What
#the R code and its result?

city_temp <- data.frame(

temp = c(42, 39, 34, 34, 30, 27),
city = c("Tuguegarao City", "Manila", "Iloilo City"," Tacloban", "Samal Island", "Davao City")
)
city_temp

#d. Associate the dataframe you have created in 2.(c) by naming the columns using
#the names() function. Change the column names by using names() function as City and
#Temperature. What is the R code and its result?

city_temp2 <- data.frame(Temperature = temp, City = city)
city_temp2 

#e. Print the structure by using str() function. Describe the output.

str(city_temp2)

  #the code's structure will show when you run it
  #the data summary is displayed

#f. From the answer in d, what is the content of row 3 and row 4 What is its R code and
#its output?
  
two_rows <- city_temp2[3:4,]
two_rows
  
  #City              #Temperature
  # Iloilo City           34
  #Tacloban               34

#g. From the answer in d, display the city with highest temperature and the city with
#the lowest temperature. What is its R code and its output?


high <- city_temp2[which.max(city_temp2$Temperature),]
high

low <- city_temp2[which.min(city_temp2$Temperature),]
low

# 1. Tuguegarao city 42
# 6. Davao city   27


#2.

#a.
  
  mtrx <- matrix(c(1:8,11:14),nrow =3, ncol = 4)
  mtrx
  
  #[,1] [,2] [,3] [,4]
  #[1,]    1    4    7   12
  #[2,]    2    5    8   13
  #[3,]    3    6   11   14
  
#b.
  
  multiply_mtrx <-mtrx*2
  multiply_mtrx
    
  #[,1] [,2] [,3] [,4]
  #[1,]    2    8   14   24
  #[2,]    4   10   16   26
  #[3,]    6   12   22   28

#c.
  
  olokolokolok <- multiply_mtrx[2,]
  olokolokolok
  
  # 4 10 16 26
  
#d.
  
  tcol_rows <- multiply_mtrx[c(1,2),c(3,4)]
  tcol_rows

#e.
  
  tcol_onerow <- multiply_mtrx[3,c(2,3)]
  tcol_onerow

  
#f.
  
  four_Col <- multiply_mtrx[,4]
  four_Col
  
#g.
  
  dimnames(multiply_mtrx) <- list(c("isa","dalawa","tatlo"),c("uno","dos","tres","quatro"))
  multiply_mtrx

  #uno dos tres quatro
  #isa      2   8   14     24
  #dalawa   4  10   16     26
  #tatlo    6  12   22     28


#h.
  
  mtrx
  dim(mtrx) <- c(6,2)
  mtrx

  #[,1] [,2]
  #[1,]    1    7
  #[2,]    2    8
  #[3,]    3   11
  #[4,]    4   12
  #[5,]    5   13
  #[6,]    6   14

#3. 
  
#a.
  
  zehaha_values <- c(1,2,3,6,7,8,9,0,3,4,5,1)
  rep_val <- rep(zehaha_values, each = 2)
  
  array <- array(rep_val, dim = c(2,4,3))
  array

  #, , 1
  
  #[,1] [,2] [,3] [,4]
  #[1,]    1    2    3    4
  #[2,]    1    2    3    4
  
  #, , 2
  
  #[,1] [,2] [,3] [,4]
  #[1,]    6    7    8    9
  #[2,]    6    7    8    9
  
  #, , 3
  
  #[,1] [,2] [,3] [,4]
  #[1,]    0    3    4    5
  #[2,]    0    3    4    5


#b.
  #it has 3 dimensions
  
  
#c.
  
  dimnames(array) <- list (
    letters [1:2],
    LETTERS [1:4],
    c("1st-Dimensional Array","2nd-Dimensional Array","3rd-Dimensional Array")
  )
    array
  
  
    #, , 1st-Dimensional Array
    
    #A B C D
    #a 1 2 3 6
    #b 1 2 3 6
    
    #, , 2nd-Dimensional Array
    
    #A B C D
    #a 7 8 9 0
    #b 7 8 9 0
    
    #3, , 3rd-Dimensional Array
    
    #A B C D
    #a 3 4 5 1
    #b 3 4 5 1
    
    
    

```

