---
title: "RWorksheet_Talon#4a"
author: "Cedric Mikhail Talon"
date: "2023-10-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


#1. The table below shows the data about shoe size and height. Create a data frame.
  
    #a. Describe the data.

    hhd <- data.frame( Shoe_Size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5 , 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
                    
                      Height = c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0),
                   
                      Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
    )
                    
    hhd
    
    #b. Create a subset by males and females with their corresponding shoe size and height.
    #What its result? Show the R scripts.
    
    MaleDF <- subset(hhd, Gender =="M")
    FemaleDF <- subset(hhd,Gender =="F")
    
    MaleDF
    FemaleDF
    
    #c. Find the mean of shoe size and height of the respondents. Write the R scripts and its
    #result.
    
    meanSS <- mean(hhd$Shoe_Size)
    meanHeight <- mean(hhd$Height)
    
    paste("the ano ah:",meanSS)
    paste("ang ano:",meanHeight)
 
    #d. Is there a relationship between shoe size and height? Why?
        
        #Yes, Because
    
    

    #2. Construct character vector months to a factor with factor() and assign the result to
#factor_months_vector. Print out factor_months_vector and assert that R prints out
#the factor levels below the actual values.
    
    months_vector <- c("March","April","January","November","January",
                              "September","October","September","November","August",
                              "January","November","November","February","May","August",
                              "July","December","August","August","September","November","February",
                                "April")
    
    months_vector
    
    
    #3
 
       factor_months_vector <- factor(months_vector)
    
    factor_months_vector
    
    #the usefulness depends on the situation
   
  factor_data <-rep(c("East","West","North"),c(1,4,3))
     
    new_order_data <- factor(factor_data,levels = c("East","West","North"))
new_order_data
    
#Enter the data below in Excel with file name = import_march.csv

#4.Create a vector and factor for the table below.

direction <- c("East", "West", "North")
frequency <- c(1,4,3)

factor_data <- factor(c(direction,frequency))
factor_data

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)

#5. 

read.table(file = "/cloud/project/RWorkSheet#4/import_march.csv", header = TRUE, sep = ",")

reading <- read.csv("import_march.csv")
reading

#6.

# Function to check if a number is in a specified range
randomNum <- readline(prompt = "Enter number from 1 to 50: ")

#error cannot knit if there is as.numeric
#randomNum <- as.numeric(randomNum)

paste("The number you have chosen is", randomNum)

if (randomNum > 50) {
  paste("The number selected is beyond the range of 1 to 50")
} else if (randomNum == 20) {
  paste("TRUE")
} else {
  paste(randomNum)
}

#7. 
minimumBills <- function(price) {
 
  min_bills <- price %/% 50
  paste("The minimum no. of bills:", min_bills)
}

minimumBills(900)

# 8.a

names <- c("Annie", "Thea", "Steve", "Hanna")
grade1 <- c(85,65,75,95)
grade2 <- c(65,75,55,75)
grade3 <- c(85,90,80,100)
grade4 <- c(100,90,85,90)

grade <- data.frame(
  Name = names,
  Grade1 = grade1,
  Grade2 = grade2,
  Grade3 = grade3,
  Grade4 = grade4
)


# 8.b

grade$Average <- (grade$Grade1 + grade$Grade2 + grade$Grade3 + grade$Grade4) / 4

average_grade <- grade[grade$Average > 90,]
average_grade

if (nrow(average_grade) > 0) {
  paste(average_grade$Name, "'s average grade this semester is", average_grade$Average)
} else {
  paste("No students have an average math score over 90.")
}

# 8.c

first_Test <- sum(grade$Grade1) / nrow(grade)
first_Test

second_Test <- sum(grade$Grade2) / nrow(grade)
second_Test

third_Test <- sum(grade$Grade3) / nrow(grade)
third_Test

fourth_Test <- sum(grade$Grade4) / nrow(grade)
fourth_Test

if (first_Test < 80) {
  paste("The 1st test was difficult.")
} else if(second_Test < 80) {
  paste("The 2nd test was difficult.")
} else if(third_Test < 80) {
  paste("The 3rd test was difficult.")
} else if(fourth_Test < 80) {
  paste("The 4th test was difficult.")
} else {
  paste("No test had an average score less than 80.")
}

# 8.d
# Annie scores
if (grade[1,2] > grade[1,3] && grade[1,2] > grade[1,4] && grade[1,2] > grade[1,5]) {
  annieHighest <- grade[1,2]
} else if (grade[1,3] > grade[1,4] && grade[1,3] > grade[1,5]) {
  annieHighest <- grade[1,3]
} else if (grade[1,4] > grade[1,5] && grade[1,2] > grade[1,5]) {
  annieHighest <- grade[1,4]
} else {
  annieHighest <- grade[1,5]
}

# Thea scores
if (grade[2,2] > grade[2,3] && grade[2,2] > grade[2,4] && grade[2,2] > grade[2,5]) {
  theaHighest <- grade[2,2]
} else if (grade[2,3] > grade[2,4] && grade[2,3] > grade[2,5]) {
  theaHighest <- grade[2,3]
} else if (grade[2,4] > grade[2,5] && grade[2,2] > grade[2,5]) {
  theaHighest <- grade[2,4]
} else {
  theaHighest <- grade[2,5]
}
# Steve scores
if (grade[3,2] > grade[3,3] && grade[3,2] >grade[3,4] && grade[3,2] > grade[3,5]) {
  steveHighest <- grade[3,2]
} else if (grade[3,3] > grade[3,4] && grade[3,3] >grade[3,5]) {
  steveHighest <- grade[2,3]
} else if (grade[3,4] > grade[3,5] && grade[3,2] > grade[3,5]) {
  steveHighest <- grade[3,4]
} else {
  steveHighest <- grade[3,5]
}

# Hanna scores
if (grade[4,2] > grade[4,3] && grade[4,2] > grade[4,4] && grade[4,2] > grade[4,5]) {
  hannaHighest <- grade[4,2]
} else if (grade[4,3] > grade[4,4] && grade[4,3] > grade[4,5]) {
  hannaHighest <- grade[2,3]
} else if (grade[4,4] > grade[4,5] && grade[4,2] > grade[4,5]) {
  hannaHighest <- grade[4,4]
} else {
  hannaHighest <- grade[4,5]
}

grade$HighestGrades <- c(annieHighest, theaHighest, steveHighest, hannaHighest)

above90 <- grade[grade$HighestGrades > 90,]
above90

if (nrow(above90) > 0) {
  paste(above90$Name, "'s highest grade this semester is", above90$HighestGrade)
} else {
  paste("No students have an average math score over 90.")
}
    
  

```